export enum AuthActionTypes {
  SET_AUTHENTICATED = 'SET_AUTHENTICATED'
}

export enum CoinActionTypes {
  SET_COINS = 'SET_COINS'
}

export enum ReferralTypes {
  GET_REFERRED_USERS_BY_ID_REQUEST = 'GET_REFERRED_USERS_BY_ID_REQUEST',
  GET_REFERRED_USERS_BY_ID_SUCCESS = 'GET_REFERRED_USERS_BY_ID_SUCCESS',
  GET_REFERRED_USERS_BY_ID_FAILED = 'GET_REFERRED_USERS_BY_ID_FAILED',

  GENERATE_REFERRAL_CODE_REQUEST = 'GENERATE_REFERRAL_CODE_REQUEST',
  GENERATE_REFERRAL_CODE_SUCCESS = 'GENERATE_REFERRAL_CODE_SUCCESS',
  GENERATE_REFERRAL_CODE_FAILED = 'GENERATE_REFERRAL_CODE_FAILED'
}

export enum ContestTypes {
  REGISTER_CONTEST_REQUEST = 'REGISTER_CONTEST_REQUEST',
  REGISTER_CONTEST_SUCCESS = 'REGISTER_CONTEST_SUCCESS',
  REGISTER_CONTEST_FAILED = 'REGISTER_CONTEST_FAILED',

  GET_CONTEST_REGISTRATION_REQUEST = 'GET_CONTEST_REGISTRATION_REQUEST',
  GET_CONTEST_REGISTRATION_SUCCESS = 'GET_CONTEST_REGISTRATION_SUCCESS',
  GET_CONTEST_REGISTRATION_FAILED = 'GET_CONTEST_REGISTRATION_FAILED',

  GET_CONTEST_RESULT_REQUEST = 'GET_CONTEST_RESULT_REQUEST',
  GET_CONTEST_RESULT_SUCCESS = 'GET_CONTEST_RESULT_SUCCESS',
  GET_CONTEST_RESULT_FAILED = 'GET_CONTEST_RESULT_FAILED'
}
